[package]
name = "explore"
version = "0.1.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

[dependencies]
strata = { path = ".." }
itertools = "0.8.0"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.39"
